/* Generated By:JJTree: Do not edit this line. ASTCatalogName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTCatalogName extends SimpleNode {
  public ASTCatalogName(int id) {
    super(id);
  }

  public ASTCatalogName(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e844124a3431955b6ff13638c6fa49d7 (do not edit this line) */
