/* Generated By:JJTree: Do not edit this line. ASTCompleteTableColumnName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTCompleteTableColumnName extends SimpleNode {
  public ASTCompleteTableColumnName(int id) {
    super(id);
  }

  public ASTCompleteTableColumnName(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9d65a6b67cb95ccb784321014eb28e72 (do not edit this line) */
