/* Generated By:JJTree: Do not edit this line. ASTColumnName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTColumnName extends SimpleNode {
  public ASTColumnName(int id) {
    super(id);
  }

  public ASTColumnName(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=983b3f16ddadad463799b3f583b21c83 (do not edit this line) */
