/* Generated By:JJTree: Do not edit this line. ASTRelop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTRelop extends SimpleNode {
  public ASTRelop(int id) {
    super(id);
  }

  public ASTRelop(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=176ac0fce6185a3f7ac7031d3c7bf81f (do not edit this line) */
