/* Generated By:JJTree: Do not edit this line. ASTSchemaName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTSchemaName extends SimpleNode {
  public ASTSchemaName(int id) {
    super(id);
  }

  public ASTSchemaName(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=064378856b959ad1e254310d545a551a (do not edit this line) */
