/* Generated By:JJTree: Do not edit this line. ASTSQLRelationalOperatorExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTSQLRelationalOperatorExpression extends SimpleNode {
  public ASTSQLRelationalOperatorExpression(int id) {
    super(id);
  }

  public ASTSQLRelationalOperatorExpression(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=50df57f3a290fbbc77f7206535b4ee2e (do not edit this line) */
