/* Generated By:JJTree: Do not edit this line. ASTSQLInClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTSQLInClause extends SimpleNode {
  public ASTSQLInClause(int id) {
    super(id);
  }

  public ASTSQLInClause(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d48fb5a4008bce495939f075b12cec60 (do not edit this line) */
