/* Generated By:JJTree: Do not edit this line. ASTSelectAlias.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTSelectAlias extends SimpleNode {
  public ASTSelectAlias(int id) {
    super(id);
  }

  public ASTSelectAlias(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d051187b13102d3e5f2bebf8e9a06762 (do not edit this line) */
