/* Generated By:JJTree: Do not edit this line. ASTSQLRelationalExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTSQLRelationalExpression extends SimpleNode {
  public ASTSQLRelationalExpression(int id) {
    super(id);
  }

  public ASTSQLRelationalExpression(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fe497d4a6ed64ea0e041e7a1eee1ed64 (do not edit this line) */
