/* Generated By:JavaCC: Do not edit this line. SqlGrammarTreeConstants.java Version 5.0 */
package org.jdbc4olap.parsing;

public interface SqlGrammarTreeConstants
{
  public int JJTQUERY = 0;
  public int JJTSELECTLIST = 1;
  public int JJTSELECTITEM = 2;
  public int JJTSELECTALIASITEM = 3;
  public int JJTSELECTSTAR = 4;
  public int JJTCOLUMNNAME = 5;
  public int JJTCOMPLETETABLECOLUMNNAME = 6;
  public int JJTTABLECOLUMNNAME = 7;
  public int JJTSELECTALIAS = 8;
  public int JJTCATALOGNAME = 9;
  public int JJTSCHEMANAME = 10;
  public int JJTTABLENAME = 11;
  public int JJTORACLEOBJECTNAME = 12;
  public int JJTFROMCLAUSE = 13;
  public int JJTTABLEREFERENCE = 14;
  public int JJTFROMITEM = 15;
  public int JJTFROMALIASITEM = 16;
  public int JJTTABLEALIAS = 17;
  public int JJTWHERECLAUSE = 18;
  public int JJTSQLRELATIONALEXPRESSION = 19;
  public int JJTSQLRELOPEXPR = 20;
  public int JJTSQLINEXPR = 21;
  public int JJTSQLRELATIONALOPERATOREXPRESSION = 22;
  public int JJTSQLSIMPLEEXPRESSION = 23;
  public int JJTRELOP = 24;
  public int JJTSQLEXPRESSIONLIST = 25;
  public int JJTSQLINCLAUSE = 26;
  public int JJTGROUPBYCLAUSE = 27;


  public String[] jjtNodeName = {
    "Query",
    "SelectList",
    "SelectItem",
    "SelectAliasItem",
    "SelectStar",
    "ColumnName",
    "CompleteTableColumnName",
    "TableColumnName",
    "SelectAlias",
    "CatalogName",
    "SchemaName",
    "TableName",
    "OracleObjectName",
    "FromClause",
    "TableReference",
    "FromItem",
    "FromAliasItem",
    "TableAlias",
    "WhereClause",
    "SQLRelationalExpression",
    "SQLRelOpExpr",
    "SQLInExpr",
    "SQLRelationalOperatorExpression",
    "SQLSimpleExpression",
    "Relop",
    "SQLExpressionList",
    "SQLInClause",
    "GroupByClause",
  };
}
/* JavaCC - OriginalChecksum=a6dd64eae5dd6c396d410f22f367cb95 (do not edit this line) */
