/* Generated By:JJTree: Do not edit this line. ASTFromAliasItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTFromAliasItem extends SimpleNode {
  public ASTFromAliasItem(int id) {
    super(id);
  }

  public ASTFromAliasItem(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a02c9163a9bfec0ba5eee3f5cd6aa5af (do not edit this line) */
