/* Generated By:JJTree: Do not edit this line. ASTFromItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTFromItem extends SimpleNode {
  public ASTFromItem(int id) {
    super(id);
  }

  public ASTFromItem(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e1cfdc25b2783ac8d6c3eef36396dde4 (do not edit this line) */
