/* Generated By:JJTree: Do not edit this line. ASTGroupByClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTGroupByClause extends SimpleNode {
  public ASTGroupByClause(int id) {
    super(id);
  }

  public ASTGroupByClause(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=02db479a2a8d4ceeb61501b055baccea (do not edit this line) */
