/* Generated By:JJTree: Do not edit this line. ASTOracleObjectName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTOracleObjectName extends SimpleNode {
  public ASTOracleObjectName(int id) {
    super(id);
  }

  public ASTOracleObjectName(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6063b8fe7fc10944b76a05b532f7929a (do not edit this line) */
