/* Generated By:JJTree: Do not edit this line. ASTQuery.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTQuery extends SimpleNode {
  public ASTQuery(int id) {
    super(id);
  }

  public ASTQuery(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=af66d734dd23f06f820a5147fbf52442 (do not edit this line) */
