/* Generated By:JJTree: Do not edit this line. ASTSelectItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTSelectItem extends SimpleNode {
  public ASTSelectItem(int id) {
    super(id);
  }

  public ASTSelectItem(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5752da8af82fe8c2eb0f1edecf69ee82 (do not edit this line) */
