/* Generated By:JJTree: Do not edit this line. ASTSQLRelOpExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTSQLRelOpExpr extends SimpleNode {
  public ASTSQLRelOpExpr(int id) {
    super(id);
  }

  public ASTSQLRelOpExpr(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=36c196d5a658ae8e7e3e777998a5578f (do not edit this line) */
