/* Generated By:JJTree: Do not edit this line. ASTSelectStar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTSelectStar extends SimpleNode {
  public ASTSelectStar(int id) {
    super(id);
  }

  public ASTSelectStar(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b17463db71477393f263d00d043ac77e (do not edit this line) */
