/* Generated By:JJTree: Do not edit this line. ASTSQLExpressionList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTSQLExpressionList extends SimpleNode {
  public ASTSQLExpressionList(int id) {
    super(id);
  }

  public ASTSQLExpressionList(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a25f23c8bf7303290e3a4d70c28fab65 (do not edit this line) */
