/* Generated By:JJTree: Do not edit this line. ASTSelectAliasItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTSelectAliasItem extends SimpleNode {
  public ASTSelectAliasItem(int id) {
    super(id);
  }

  public ASTSelectAliasItem(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=862749a39c64253da0dbc784ad5fdf13 (do not edit this line) */
