/* Generated By:JJTree: Do not edit this line. ASTSQLSimpleExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTSQLSimpleExpression extends SimpleNode {
  public ASTSQLSimpleExpression(int id) {
    super(id);
  }

  public ASTSQLSimpleExpression(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ed8f240aea752a77e2bdf41f9dd17983 (do not edit this line) */
