/* Generated By:JJTree: Do not edit this line. ASTSQLInExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTSQLInExpr extends SimpleNode {
  public ASTSQLInExpr(int id) {
    super(id);
  }

  public ASTSQLInExpr(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f2ee298510b8f1d97e02c4b662e8c1b6 (do not edit this line) */
