/* Generated By:JJTree: Do not edit this line. ASTTableColumnName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTTableColumnName extends SimpleNode {
  public ASTTableColumnName(int id) {
    super(id);
  }

  public ASTTableColumnName(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b39d7cee1b379a614730972829769ce6 (do not edit this line) */
