/* Generated By:JJTree: Do not edit this line. ASTTableName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jdbc4olap.parsing;

public
class ASTTableName extends SimpleNode {
  public ASTTableName(int id) {
    super(id);
  }

  public ASTTableName(SqlGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8541a5a9e519957d5ad3d502ab6f11c0 (do not edit this line) */
